[package]
name = "match3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.3"
nohash-hasher = "0.2.0"
smallvec = "1.13.2"
strum = { version = "0.26.2", features = ["derive"] }
