disallowed-methods = [
    # f32 - Platform-specific precision
    "f32::powi",
    "f32::powf",
    "f32::exp",
    "f32::exp2",
    "f32::ln",
    "f32::log",
    "f32::log2",
    "f32::log10",
    "f32::log10",
    "f32::hypot",
    "f32::sin",
    "f32::cos",
    "f32::tan",
    "f32::asin",
    "f32::acos",
    "f32::atan",
    "f32::atan2",
    "f32::sin_cos",
    "f32::exp_m1",
    "f32::ln_1p",
    "f32::sinh",
    "f32::cosh",
    "f32::tanh",
    "f32::asinh",
    "f32::acosh",
    "f32::atanh",
    "f32::gamma",
    "f32::ln_gamma",
    # f64 - Platform-specific precision
    "f64::powi",
    "f64::powf",
    "f64::exp",
    "f64::exp2",
    "f64::ln",
    "f64::log",
    "f64::log2",
    "f64::log10",
    "f64::log10",
    "f64::hypot",
    "f64::sin",
    "f64::cos",
    "f64::tan",
    "f64::asin",
    "f64::acos",
    "f64::atan",
    "f64::atan2",
    "f64::sin_cos",
    "f64::exp_m1",
    "f64::ln_1p",
    "f64::sinh",
    "f64::cosh",
    "f64::tanh",
    "f64::asinh",
    "f64::acosh",
    "f64::atanh",
    "f64::gamma",
    "f64::ln_gamma",
]